---
- name: Hello World
  ansible.builtin.debug:
    msg: "Hello World"

- name: Just a Test
  ansible.builtin.debug:
    msg: "This is just a test!"
    verbosity: 1

- name: It is a Test
  ansible.builtin.debug:
    msg: "Srsly guys, i's just a test. Go away!"
    verbosity: 2

- name: Copy Template
  become: true
  ansible.builtin.template:
    src: templates/hello.txt.j2
    dest: /tmp/hello_world.txt
    mode: 0644
    owner: root
    group: root
