---
name: Galaxy release

# yamllint disable-line rule:truthy
on:
  release:
    types: ['created']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout git repo'
        uses: actions/checkout@v4.1.1
        with:
          lfs: true
          submodules: true
          fetch-depth: 0

      - name: "Publish Ansible"
        uses: ansible/ansible-publish-action@v1.0.0
        with:
          api_key: "${{ secrets.GALAXY_API_KEY }}"
